apiVersion: v1
kind: Service

metadata:
  name: prom-svc
  labels: 
    env: metrics
  
spec:
  ports:
    - port: 9090
      nodePort: 31000
  selector:
    env: metrics

  type: NodePort